config/routes.rb
Rails.application.routes.draw do

  root 'people#home'

  resources :people do
    member do
      patch :change_availablity
    end
  end
  resources :tasks do
    collection do
      get :search
      get :results
    end
    member do
      patch :change_complete_status
    end
    
  end

end

app/models/person.rb
class Person < ActiveRecord::Base

	has_many :tasks

	mount_uploader :person_photo, PersonPhotoUploader
	
end

app/models/task.rb
class Task < ActiveRecord::Base

	belongs_to :person

	mount_uploader :task_photo, TaskPhotoUploader

	scope :task_completed, -> {where(complete: true)}
	scope :task_incomplete, -> {where(complete: false)}
	
	def self.start_date(start_date)
		where('due_date > ?' , start_date)
	end

	def self.end_date(end_date)
		where('due_date < ?' , end_date)
	end

	def self.person(person)
		joins(:person).where('people.name Like ?', person)
	end

	def self.search(params)
		
		user_input = params[:search]
		start_date = params[:start_date]
		end_date = params[:end_date]
		person = params[:person]
		task_completed = params[:task_completed]
		search = Task.all

		if person.present? 
			 search = search.person(person)
		end

		if task_completed.present?
				if task_completed == "true"
					search = search.task_completed
				else
					search = search.task_incomplete
				end
		end

		if start_date.present?
				search = search.start_date(start_date)
			end

		if end_date.present?
			search = search.end_date(end_date)
		end

		if user_input != " "
				search = search.where('tasks.name Like ?' , "%#{user_input}%" )
		end

		
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

	def index
		@people = Person.all
	end

	def new
		@new_person = Person.new
	end

	def create
		@new_person = Person.new(person_params)
		if @new_person.save
			redirect_to people_path
		else
			redirect_to new_person_path
		end
	end

	def show
		@person = Person.find(params[:id])
		@person_id = @person.id
		@tasks = Task.where('tasks.person_id = ?' , @person_id)
		
	end

	def edit
		@person = Person.find(params[:id])
	end

	def update
		@person = Person.find(params[:id])
		if @person.update_attributes(person_params)
			redirect_to people_path
		end
	end

	def destroy
		@person = Person.find(params[:id])
		if @person.destroy
			redirect_to people_path
		end
	end

	def change_availablity
		@person = Person.find(params[:id])
		if @person.available 
			val = false
		else
			val = true
		end
		@person.update_attributes(:available => val)
		redirect_to person_path(params[:id])
	end

	private

	def person_params
		params.require(:person).permit!
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@tasks = Task.all
	end

	def new
		@new_task = Task.new
	end

	def create
		@new_task = Task.new(task_params)
		if @new_task.save
			redirect_to tasks_path
		else
			redirect_to new_task_path
		end
	end

	def show
		@task = Task.find(params[:id])
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
		@task = Task.find(params[:id])
		if @task.update_attributes(task_params)
			redirect_to tasks_path
		end
	end

	def destroy
		@task = Task.find(params[:id])
		if @task.destroy
			redirect_to tasks_path
		end
	end

	def search
		@tasks = Task.search(params[:search])
		render :index 
	end

		def change_complete_status
		@task = Task.find(params[:id])
		if @task.complete
			val = false
		else
			val = true
		end
		@task.update_attributes(:complete => val)
		redirect_to :back
	end



	private

	def task_params
		params.require(:task).permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/person_helper.rb
module PersonHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoSearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.haml
= f.label :name
= f.text_field :name
%br
= f.label :available
= f.check_box :available
%br

= f.submit "Add"

app/views/people/_taskinfo.html.haml
Name:
= t.name
%br
Due Date:
= t.due_date
%br
Description:
= t.description
%br
Completed?:
-if t.complete
	= link_to "this task is complete",
			change_complete_status_task_path, method: 'patch'
-else 
	= link_to "this task in incomplete",
			change_complete_status_task_path, method: 'patch'
%br
=link_to "Edit this task", "/tasks/#{t.id}/edit"	
%br

app/views/people/edit.html.haml
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}
		%meta{:charset => "utf-8"}
			%title Bootply.com - Bootstrap Bootstrap Login Form
			%title http://bootstrapzero.com/bootstrap-template/sign-in
			%meta{:content => "Bootply", :name => "generator"}/
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
				%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css", :rel => "stylesheet"}
				/[if lt IE 9]
				<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
				%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon.png", :rel => "apple-touch-icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}

%body
	.navbar.navbar-inverse.navbar-fixed-top 
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

		#loginModal.modal.show{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", :style => "\n    margin-top: 55px;\n    margin-left: 0px;\n"}
			.modal-dialog
				.modal-content
					.modal-header
						%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
						%h1.text-center Edit Family Member
					.modal-body
						= form_for @person, url: "/people/#{@person.id}" do |f|
							= f.file_field :person_photo
							= render "form", f: f
							%br

app/views/people/home.html.haml
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title Siimple - Free Bootstrap 3 Landing Page
    / Bootstrap
    %link{href: "http://bootstraptaste.com/theme/siimple/assets/css/style.css", rel: "stylesheet"}/

  %body
    / Fixed navbar
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: "http://localhost:3000"} & Done
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{href: "/tasks/new"} Start A Task
            %li
              %a{href: "http://localhost:3000/people"} Your Family
        / /.nav-collapse
    #header
      .container
        .row
          .col-lg-6
            %h1 Finish Your Task, & Done
            %form.form-inline.signup{role: "form"}
              .form-group
                %input#exampleInputEmail1.form-control{placeholder: "Enter your email address", type: "email"}/
              %button.btn.btn-theme{type: "submit"} Get it now

    #footer
      .container
        .row
          .col-lg-6.col-lg-offset-3
            %p.copyright Dan Cornnell & Chris Turner, 2014

    %script{src: "https://code.jquery.com/jquery-1.10.2.min.js"}
    %script{src: "assets/js/bootstrap.min.js"}

app/views/people/index.html.haml
%html
	%head
		%meta{:charset => "utf-8"}
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
			%meta{:content => "Bootstrap templates: Free, responsive and ready to kickstart your Bootstrap development - for Bootstrap 3", :name => "description"}/
			%meta{:content => "Bootstrap,templates,Twitter Bootstrap templates,free,Bootstrap 3,example,snippet", :name => "keywords"}/
			%title Bootstrap Templates from Bootply - The Bootstrap Playground
			%link{:href => "https://plus.google.com/116497776225182131214", :rel => "author"}/
			%link{:href => "https://plus.google.com/+Bootply", :rel => "publisher"}/
			%meta{:content => "https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905_bigger.jpeg", :name => "og:image"}/
			%link{:href => "http://getbootstrap.com/dist/css/bootstrap.css", :rel => "stylesheet"}
			%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet", :type => "text/css"}
			/[if lt IE 9]
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
			%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
			%link{:href => "http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}
			%link{:href => "http://www.bootply.com/css/blog.css", :rel => "stylesheet", :type => "text/css"}
			%link{href: "http://bootstraptaste.com/theme/siimple/assets/css/style.css", rel: "stylesheet"}/

:javascript
	var z = document.createElement("script"); z.type = "text/javascript"; z.async = true; z.src = "http://engine.carbonads.com/z/32644/azcarbon_2_1_0_VERT"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(z, s);  

%body
	.navbar.navbar-inverse.navbar-fixed-top
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

	#main.column.col-sm-9
		.padding
			.full.col-sm-9
				.col-sm-12
					#templates.page-header.text-muted
						Your Family |
						%small - Keep track of who's doing what
						= button_to "Add Someone", new_person_path, method: "get"

				.row
					.col-sm-8
						%h3
							%span.badge.badge-default 
							- @people.each do |p|
								Name:
								=link_to "#{p.name}" , "people/#{p.id}"

								%br
								-if p.available
									This Person is Available
								-else 
									This Person is Not Available

								%hr
								%br

#footer
	.container
		.row
			.col-lg-6.col-lg-offset-3
				%p.copyright Dan Cornnell & Chris Turner, 2014

app/views/people/new.html.haml
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}
		%meta{:charset => "utf-8"}
			%title Bootply.com - Bootstrap Bootstrap Login Form
			%title http://bootstrapzero.com/bootstrap-template/sign-in
			%meta{:content => "Bootply", :name => "generator"}/
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
				%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css", :rel => "stylesheet"}
				/[if lt IE 9]
				<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
				%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon.png", :rel => "apple-touch-icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
				%link{href: "http://bootstraptaste.com/theme/siimple/assets/css/style.css", rel: "stylesheet"}/

%body
	.navbar.navbar-inverse.navbar-fixed-top 
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

		#loginModal.modal.show{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", :style => "\n    margin-top: 55px;\n    margin-left: 0px;\n"}
			.modal-dialog
				.modal-content
					.modal-header
						%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
						%h1.text-center Add Family Member
					.modal-body
						= form_for @new_person do |f|
							= f.file_field :person_photo
							%br
							= render "form", f: f

							

app/views/people/show.html.haml
%html{lang: "en"}
	%head
		%meta{charset: "utf-8"}/
		%meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
		%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
		%meta{content: "", name: "description"}/
		%meta{content: "", name: "author"}/
		%link{href: "http://www.blacktie.co/docs-assets/ico/favicon.png", rel: "shortcut icon"}/
		%title STANLEY - Free Bootstrap Theme
		/ Bootstrap core CSS
		%link{href: "http://www.blacktie.co/demo/stanley/assets/css/bootstrap.css", rel: "stylesheet"}/
		/ Custom styles for this template
		%link{href: "http://www.blacktie.co/demo/stanley/assets/css/main.css", rel: "stylesheet"}/
		%script{src: "https://code.jquery.com/jquery-1.10.2.min.js"}
		%script{src: "assets/js/hover.zoom.js"}
		%script{src: "assets/js/hover.zoom.conf.js"}
#ww
	.container
		.row
			.col-lg-8.col-lg-offset-2.centered
				%img
				= image_tag @person.person_photo.url
				%h1 #{@person.name}
				%p Hello everybody. I'm #{@person.name}, task-doer extraordinaire.  Check out all the amazing tasks I've completed since joining &Done!
				= button_to "Delete Profile", "/people/#{@person.id}", {:action => "delete", :method => :delete}
				=button_to "Edit Profile", "/people/#{@person.id}/edit", {:method => :get}
          
.container.pt
	.row.mt.centered
		- @person.tasks.each do |t|
			-if t.complete 
				.button-show
					%button.btn.btn-default
						=render 'taskinfo', t: t
			-else 
				.button-show
					%button.btn.btn-danger
						=render 'taskinfo', t: t

app/views/tasks/_form.html.haml
= f.label :name
= f.text_field :name
%br
= f.label :complete
= f.check_box :complete
%br
= f.label :due_date
= f.date_select :due_date
%br
= f.label :description
= f.text_area :description
%br

= f.label "person"
= f.select :person_id, Person.all.collect {|p| [p.name, p.id]} #===> p.name is what displays, p.id is what is returned
%br
= f.submit "Add"

app/views/tasks/edit.html.haml
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}
		%meta{:charset => "utf-8"}
			%title Bootply.com - Bootstrap Bootstrap Login Form
			%title http://bootstrapzero.com/bootstrap-template/sign-in
			%meta{:content => "Bootply", :name => "generator"}/
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
				%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css", :rel => "stylesheet"}
				/[if lt IE 9]
				<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
				%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon.png", :rel => "apple-touch-icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}

%body
	.navbar.navbar-inverse.navbar-fixed-top 
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

		#loginModal.modal.show{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", :style => "\n    margin-top: 55px;\n    margin-left: 0px;\n"}
			.modal-dialog
				.modal-content
					.modal-header
						%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
						%h1.text-center Edit Task
						= form_for @task, url: "/tasks/#{@task.id}" do |f|
							= f.file_field :task_photo
							= render "form", f: f

app/views/tasks/index.html.haml
/ %h1 List of Tasks

/ - @tasks.each do |t|
/ 	Name:
/ 	= t.name
/ 	%br
/ 	Due Date:
/ 	= t.due_date
/ 	%br
/ 	Description:
/ 	= t.description
/ 	%br
/ 	Completed?:
/ 	-if t.complete
/ 		This Task Has Been Completed
/ 	-else 
/ 		This Task Has Not Been Completed
/ 	%br
/ 	Assigned to:
/ 	-if t.person
/ 		= t.person.name
/ 	-else
/ 		No Person Has Been Assigned To This Task
/ 	%br
/ 	%br

%html
	%head
		%meta{:charset => "utf-8"}
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
			%meta{:content => "Bootstrap templates: Free, responsive and ready to kickstart your Bootstrap development - for Bootstrap 3", :name => "description"}/
			%meta{:content => "Bootstrap,templates,Twitter Bootstrap templates,free,Bootstrap 3,example,snippet", :name => "keywords"}/
			%title Bootstrap Templates from Bootply - The Bootstrap Playground
			%link{:href => "https://plus.google.com/116497776225182131214", :rel => "author"}/
			%link{:href => "https://plus.google.com/+Bootply", :rel => "publisher"}/
			%meta{:content => "https://pbs.twimg.com/profile_images/3663020003/d09fae59ab68605a7973043e0267b905_bigger.jpeg", :name => "og:image"}/
			%link{:href => "http://getbootstrap.com/dist/css/bootstrap.css", :rel => "stylesheet"}
			%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", :rel => "stylesheet", :type => "text/css"}
			/[if lt IE 9]
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
			%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
			%link{:href => "http://netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}
			%link{:href => "http://www.bootply.com/css/blog.css", :rel => "stylesheet", :type => "text/css"}
			%link{href: "http://bootstraptaste.com/theme/siimple/assets/css/style.css", rel: "stylesheet"}/
:javascript
	var z = document.createElement("script"); z.type = "text/javascript"; z.async = true; z.src = "http://engine.carbonads.com/z/32644/azcarbon_2_1_0_VERT"; var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(z, s);  

%body
	.navbar.navbar-inverse.navbar-fixed-top 
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

.search{:style => "\n    padding-bottom: 55px;\n    margin-left: 0px;\n"}
= form_tag search_tasks_path, method: "get" do
	= label_tag "search tasks"
	= text_field_tag "search[search]"
	= label_tag "person assigned to task"
	=	select_tag 'search[person]', options_for_select(Person.pluck(:name)),include_blank: true
	=	label_tag "check only completed tasks"
	=	select_tag "search[task_completed]", options_for_select([['complete', true],['incomplete', false]]), include_blank: true
	= label_tag "look for tasks that are due after:"
	= date_field_tag "search[start_date]"	
	= label_tag "look for tasks that are due before:"
	= date_field_tag "search[end_date]"
	= submit_tag "search"

	

	#main.column.col-sm-9
		.padding
			.full.col-sm-9
				.col-sm-12
					#templates.page-header.text-muted
						Task List |
						%small Get back to what's important.
						= button_to "Add New Task", new_task_path, method: "get"

				.row
					.col-sm-8
						%h3
							%span.badge.badge-default 
							- @tasks.each do |t|
								Task:
								=link_to "#{t.name}" , "tasks/#{t.id}"
								%br
								Due Date:
								= t.due_date
								%br
								Description:
								= t.description
								%br
								Completed?:
								-if t.complete
									Yes
								-else 
									No
								%br
								Assigned to:
								-if t.person
									= t.person.name
								-else
									Not Specified
								%hr
								%br


#footer
	.container
		.row
			.col-lg-6.col-lg-offset-3
				%p.copyright Dan Cornnell & Chris Turner, 2014

/ %body
/ 	.wrapper
/ 		.box
/ 			.row
/ 			#sidebar.column.col-sm-3
/ 				%a.logo{:href => "http://www.bootply.com"} &Done
/ 				%ul.nav
/ 					%li.active
/ 						%a{:href => "http://www.bootply.com/templates#templates"} Tasks
/ 					%li
/ 						%a{:href => "http://www.bootply.com/templates#howto"} People

/ 					%ul#sidebar-footer.nav.hidden-xs
/ 						%li
/ 							%a{:href => "http://www.bootply.com", :target => "_new"}
/ 							%h3> &Done
/ 							Get back to what's important.

app/views/tasks/new.html.haml
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "content-type"}
		%meta{:charset => "utf-8"}
			%title Bootply.com - Bootstrap Bootstrap Login Form
			%title http://bootstrapzero.com/bootstrap-template/sign-in
			%meta{:content => "Bootply", :name => "generator"}/
			%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}
				%link{:href => "http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css", :rel => "stylesheet"}
				/[if lt IE 9]
				<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
				%link{:href => "http://www.bootply.com/bootstrap/img/favicon.ico", :rel => "shortcut icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon.png", :rel => "apple-touch-icon"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}
				%link{:href => "http://www.bootply.com/bootstrap/img/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}
				%link{href: "http://bootstraptaste.com/theme/siimple/assets/css/style.css", rel: "stylesheet"}/

%body
	.navbar.navbar-inverse.navbar-fixed-top 
		.container
			.navbar-header
				%button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
					%span.icon-bar
					%span.icon-bar
					%span.icon-bar
				%a.navbar-brand{href: "http://localhost:3000"} & Done
			.navbar-collapse.collapse

		#loginModal.modal.show{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1", :style => "\n    margin-top: 55px;\n    margin-left: 0px;\n"}
			.modal-dialog
				.modal-content
					.modal-header
						%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
						%h1.text-center Add A Task
					.modal-body
						= form_for @new_task do |f|
							= f.file_field :task_photo
							%br
							= render "form", f: f
							%br

app/views/tasks/show.html.haml
%html{lang: "en"}
	%head
		%meta{charset: "utf-8"}/
		%meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
		%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
		%meta{content: "", name: "description"}/
		%meta{content: "", name: "author"}/
		%link{href: "http://www.blacktie.co/docs-assets/ico/favicon.png", rel: "shortcut icon"}/
		%title STANLEY - Free Bootstrap Theme
		/ Bootstrap core CSS
		%link{href: "http://www.blacktie.co/demo/stanley/assets/css/bootstrap.css", rel: "stylesheet"}/
		/ Custom styles for this template
		%link{href: "http://www.blacktie.co/demo/stanley/assets/css/main.css", rel: "stylesheet"}/
		%script{src: "https://code.jquery.com/jquery-1.10.2.min.js"}
		%script{src: "assets/js/hover.zoom.js"}
		%script{src: "assets/js/hover.zoom.conf.js"}
#ww
	.container
		.row
			.col-lg-8.col-lg-offset-2.centered
				%img
				= image_tag @task.task_photo.url
				%h1 #{@task.name}
				%p #{@task.description}
				%br
				-if @task.complete
					This Task Has Been Completed.
				-else 
					This Task Has Not Been Completed.
				%br
				= button_to "Delete", "/tasks/#{@task.id}", {:action => "delete", :method => :delete}
				%br
				=button_to "Edit Task", "/tasks/#{@task.id}/edit", {:method => :get} 
				%br
				=button_to "Completed?", change_complete_status_task_path, {:method => :patch}